[package]
name = "terryc_base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.1.0"
salsa = "0.16.1"
ariadne = "0.1.5"
index_vec = "0.1.3"
typed-arena = "2.0.1"
